
# Logo
logo_image_source: /images/logo.svg

# Index Page
index_banner_text: Uncensored Internet Access is a basic human right.
index_banner_text_secondary: Uncensored, Neutral, Secured
index_font_awesome_icon_css: fa fa-lock

# Header
menu:
  Home: /
  News: /news/
  # Categories: /categories
  About: /about/
  Contact: /contact/

# Post
default_post_title: 404 TITLE NOT FOUND
default_post_icon: fa-file-text-o

# Archive Date Format
archive_date_format: MM/DD/YYYY
archive_font_awesome_icon_css: fa-folder-open

# About Widget
about_widget_avatar_url: /images/avatar.svg
about_widget_text: "Your humble private Internet security advisor since 2017"


# Comments.
comments:
  # Disqus comments
  disqus_shortname: 

# Google Analytics Tracking ID
google_analytics:

# Social Media Platforms
social_platforms:
  - url: https://twitter.com/tunnelwork
    fa_icon: fa-twitter
  - url: https://github.com/TunnelWork
    fa_icon: fa-github
  - url: https://t.me/tunnelwork
    fa_icon: fa-telegram
  - url: mailto:contact@tunnel.work
    fa_icon: fa-envelope

# Footer about
footer_about: "@Tunnel.Work All right reserved | Design & Hexo <a class=\"link dim white\" href=\"http://www.codeblocq.com/\">Jonathan Klughertz</a>"
